export type TipoEventoAuditoria =
  | "CLIENTE_CREADO"
  | "CLIENTE_ELIMINADO"
  | "CLIENTE_ELIMINACION_BLOQUEADA"
  | "ENVIO_CREADO"
  | "ENVIO_ELIMINADO"
  | "ENVIO_ELIMINACION_BLOQUEADA"
  | "ENVIO_ESTADO_CAMBIADO"
  | "ENVIO_ESTADO_BLOQUEADO"
  | "INGRESO_CREADO"
  | "INGRESO_ELIMINADO"
  | "INGRESO_CREACION_BLOQUEADA"
  | "FACTURA_EMITIDA"
  | "FACTURA_ELIMINADA"
  | "FACTURA_COBRADA"
  | "FACTURA_ANULADA"
  | "CORTE_FACTURACION_EMITIDO"
  | "GASTO_VEHICULO_CREADO"
  | "GASTO_VEHICULO_ELIMINADO"
  | "PAGO_AYUDANTE_CREADO"
  | "PAGO_AYUDANTE_ELIMINADO"
  | "CONFIGURACION_ACTUALIZADA"
  | "BACKUP_EXPORTADO"
  | "BACKUP_IMPORTADO";

export type EventoAuditoria = {
  id: string;
  fecha: string;
  tipo: TipoEventoAuditoria;
  descripcion: string;
  entidad?: string;
  entidadId?: string;
};